### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by andrewlew1s** [andrewlew1s/hmc-transcribers#3]
**HEY ALL** 

Please report bugs here! Thanks.

**Comment by andrewlew1s** [comment]
How to:

If you find a bug. Report it here. Or make a new issue if it's a big deal.

**Comment by hmc-cs-mstreinz** [comment]
Bug with transcribing a second card. Fields that were populated by the first card and not explicitly overwritten with the new results are still present in the output. @andrewlew1s

**Comment by andrewlew1s** [comment]
> Bug with transcribing a second card. Fields that were populated by the first card and not explicitly overwritten with the new results are still present in the output. @andrewlew1s

This should be fixed!

**Comment by hmc-cs-mstreinz** [comment]
Hey @andrewlew1s sometimes when uploading the call to firebase returns a 404 and it doesn't get the photo. However, pressing the button again will make it work

**Comment by andrewlew1s** [comment]
> Hey @andrewlew1s sometimes when uploading the call to firebase returns a 404 and it doesn't get the photo. However, pressing the button again will make it work

Couldn't get this to happen @hmc-cs-mstreinz - make you're clicking the button too fast?

**Comment by ievans-HMC** [comment]
@andrewlew1s weren’t we having this issue in class today where sometimes if you click it it doesn’t actually upload?

**Comment by hmc-cs-mstreinz** [comment]
On the front end previous results are still showing up if you don't transcribe a card in between going to the home page and returning to results. I don't know if this is necessarily a bug since nothing should replace those values it just seems odd that they're still there

**Comment by andrewlew1s** [comment]
@all The above issues should now be fixed :)
